#' Makes a treemap based on data exported by REVIGO
#'
#' @details This function is based on the original R scripts that are being
#' generated by REVIGO \url{(http://revigo.irb.hr/revigo.jsp)}.
#' 
#' @param revigo.data the result of \code{\link{GOrilla2REVIGO}}, i.e. a data.frame
#' with GO terms and the respective REVIGO stats
#' @param col_palette which color palette to use, e.g. "Paired" (default),
#' "Spectral", "Accent", "Set1", "Set2", "-RdGy", or \code{terrain.colors(10)}
#' @param title title to be printed on top of the plot
#' @param ... additional parameters for \code{treemap::treemap}
#'
#' @examples \dontrun{
#' revigo.data <- rbind(c("GO:0005576","extracellular region",4.572,5.7113,0.960,0.000,"extracellular region"),
#'                     c("GO:0005623","cell",64.133,17.3884,0.985,0.000,"cell"),
#'                     c("GO:0005739","mitochondrion",3.808,17.2418,0.442,0.000,"mitochondrion"),
#'                     c("GO:0045251","electron transfer flavoprotein complex",0.000,4.1740,0.845,0.183,"mitochondrion"),
#'                     c("GO:0005737","cytoplasm",38.159,31.1624,0.773,0.221,"mitochondrion"),
#'                     c("GO:0017133","mitochondrial electron transfer flavoprotein complex",0.000,4.1740,0.684,0.234,"mitochondrion"))
#'
#' REVIGO_treemap(revigo.data, title="REVIGO treemap: cellular components")
#' }
#' 
#' @seealso \code{\link{GOrilla2Revigo}}
#'
#' @export
#'
REVIGO_treemap <- function(revigo.data, col_palette = "Paired",
                           title = "REVIGO Gene Ontology treemap", ...){

  stuff <- data.frame(revigo.data)
  names(stuff) <- c("term_ID","description","freqInDbPercent","abslog10pvalue",
                    "uniqueness","dispensability","representative")

  stuff$abslog10pvalue <- as.numeric( as.character(stuff$abslog10pvalue) )
  stuff$freqInDbPercent <- as.numeric( as.character(stuff$freqInDbPercent) )
  stuff$uniqueness <- as.numeric( as.character(stuff$uniqueness) )
  stuff$dispensability <- as.numeric( as.character(stuff$dispensability) )

  # check the treemap command documentation for all possible parameters - there are a lot more
  treemap::treemap(
    stuff,
    index = c("representative","description"),
    vSize = "abslog10pvalue",
    type = "categorical",
    vColor = "representative",
    title = title,
    inflate.labels = FALSE,      # set this to TRUE for space-filling group labels - good for posters
    lowerbound.cex.labels = 0,   # try to draw as many labels as possible (still, some small squares may not get a label)
    bg.labels = 255, # define background color of group labels; here: transparency set to maximum
    # "#CCCCCC00" is fully transparent, "#CCCCCCAA" is semi-transparent grey, NA is opaque
    position.legend = "none",
    fontsize.title = 22, fontsize.labels=c(18,12,8),
    #fontcolor.labels=c("black","white","white"),
    palette= col_palette, ...
  )

}
